### ISSUE TITLE
How to resolve it this Docker issue

### ISSUE THREAD

**Issue by JKAngular** [avatsaev/angular-contacts-app-example-api#10]
Hi
How to resolve it can you guide me

![image](https://user-images.githubusercontent.com/59573064/82108377-a97b6880-974b-11ea-82b7-c75b79b57e8d.png)

**Comment by avatsaev** [comment]
Install docker and docker-compose  on your system

**Comment by JKAngular** [comment]
Hi,
can you share the URL for download and install and further

**Comment by avatsaev** [comment]
https://www.docker.com/get-started
